# https://taskfile.dev

version: '3'

tasks:
  setup: 
    cmds:
      - go mod download
      - go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      - go install github.com/fatih/gomodifytags@latest
  regen:
    cmds:
      - oapi-codegen -generate="types,server,strict-server,spec" -package autogen ../bar.openapi.yml > autogen/bar.gen.go
      - go mod tidy
      - gomodifytags -all -file ./autogen/bar.gen.go -add-tags bson -w > /dev/null
  update-helloasso:
    desc: Update the helloasso api
    cmds:
      - curl --fail -o autogen/helloasso/helloasso.openapi.json https://raw.githubusercontent.com/HelloAsso/helloasso-open-api/refs/heads/main/helloasso.json
      - oapi-codegen -generate="models,types,client" -package helloasso autogen/helloasso/helloasso.openapi.json > autogen/helloasso/helloasso.gen.go
      - go mod tidy
      - gomodifytags -all -file ./autogen/helloasso/helloasso.gen.go -add-tags bson -w > /dev/null
