version: "3"

tasks:
  build:
    desc: "Build Alpine image"
    cmds:
      - echo "[Building Alpine image]"
      - docker build -o build .
  test:
    desc: "Test Alpine image"
    cmds:
      - wget -nc https://github.com/clearlinux/common/raw/master/OVMF.fd
      # start with network
      - qemu-system-x86_64 -hda build/image.img -smp 4 -m 2G -bios OVMF.fd -nic user,model=virtio-net-pci
  clean:
    desc: "Clean Alpine image"
    ignore_error: true
    cmds:
      - echo "[Cleaning Alpine image]"
      - docker rm `docker ps -qa -f=label=project="bar-borne"`
      - docker rmi `docker images -q bar/*`